### ISSUE TITLE
vite and mui compatibality issue

### ISSUE THREAD

**Issue by rozhanroukhosh** [vitejs/vite-plugin-react#175]
### Describe the bug

when I run my application which uses MUI, i get this error from vite in the console
![image](https://github.com/vitejs/vite-plugin-react/assets/31434728/1b790b84-36ea-43d6-959f-59afe988db8d)
is there any fix for this?

my "dependencies": {
    "@emotion/react": "^11.11.0",
    "@emotion/styled": "^11.11.0",
    "@mui/icons-material": "^5.11.16",
    "@mui/material": "^5.13.3",
    "material-icons": "^1.13.7",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-router-dom": "^6.11.2"
  },

### Steps to reproduce

npm run dev

### System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz  
    Memory: 23.63 GB / 31.76 GB
  Binaries:
    Node: 18.16.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.5.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (114.0.1823.37)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @vitejs/plugin-react: ^4.0.0 => 4.0.0
    vite: ^4.3.2 => 4.3.9
```

### Used Package Manager

npm

### Logs

Uncaught TypeError: undefined is not a function
    <anonymous> Grid2.js:5

### Validations

- [ ] Follow our [Code of Conduct](https://github.com/vitejs/vite-plugin-react/blob/main/CODE_OF_CONDUCT.md)
- [ ] Read the [Contributing Guidelines](https://github.com/vitejs/vite-plugin-react/blob/main/CONTRIBUTING.md).
- [ ] Read the [docs](https://vitejs.dev/guide).
- [ ] Check that there isn't [already an issue](https://github.com/vitejs/vite-plugin-react/issues) that reports the same bug to avoid creating a duplicate.
- [ ] Make sure this is a Vite issue and not a framework-specific issue.
- [ ] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite-plugin-react/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [ ] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ArnaudBarre** [comment]
Can you provide a small repro on stackblitz? Maybe you need to set [jsxImportSource](https://github.com/vitejs/vite-plugin-react/blob/main/packages/plugin-react/README.md#jsximportsource)

**Comment by rozhanroukhosh** [comment]
@ArnaudBarre after reporting this issue, I found the solution, the problem comes randomly with importing grid2 from mui.  @syakuis  on  issue (https://github.com/mui/material-ui/issues/32727)) has posted the solution ,  which I quote "I solved it like this

```
import Grid from '@mui/material/Unstable_Grid2'; (Error)

import Grid from '@mui/material/Unstable_Grid2/Grid2'; (Good)
```

and

./node_modules/.vite <---- delete
`
$ npm run dev`
"

**Comment by stee-ren** [comment]
@rozhanroukhosh We're hitting this issue and we don't use @mui/material/Unstable_Grid2. I tried other suggestions, in the same ticket you referenced above, which showed hope, but in the end, it didn't amount to anything. 

Our known work around for this is currently to delete the node_modules/.vite folder and restart vite with --force. 
However, recently, this has not reliably worked. In the last few days, I I had to do this 3-4 times (in a row) before I got my Web app running again. 

As I see it, something goes bad when building the chunks, probably to do with dependency ordering. Nearly all of the suggestions I saw in the MUI ticket https://github.com/mui/material-ui/issues/32727 seem to be just another way of triggering the respective chunks to get rebuilt - and in their case, clearing the issue. It has been our experience that this it WILL inevitably re-occur (most likely when node module dependencies have been changed). 

I hope you can re-plan this ticket because I would really love a fix from the Vite side, otherwise even if MUI changes things to avoid this, there's nothing to stop his popping back up again with another library (or again with MUI months from now).

**Comment by rozhanroukhosh** [comment]
@stee-ren I am also sometimes rerunning to this issue and currently i do the same removing the vite module.
A solution a colleague of mine yesterday tried was to remove "^" from all the dependencies of package.json so that vite doesn't auto update the packages, I have to say i didn't still tried this way so i cannot confirm whether it will work or not. but what i can confirm is vite is trying to optimize the package and then the problem starts. I hope vite team can solve this. @ArnaudBarre

**Comment by stee-ren** [comment]
We do not allow dependencies with ~ or ^ on our package.json (for security reasons). Of course this allow everything to work consistently until someone updates our dependencies (we do this approx every 2 weeks), or we're adding/removing a dependency. Then this issue will randomly effect all other developers on the team.

**Comment by ArnaudBarre** [comment]
@rozhanroukhosh Vite doesn't touch your packge.json nor your dependencies version. This is the role of your package manager, and you should commit the lockfile to avoid bumps from dependencies (using exact version in package.json is not enough)

Reading the issue it seems that most people encounter the issue because of icons and force optimising them  seems to solve the issue.

There is probably a bug in vite optmizer, if you want it to be fixed, please create an issue on Vite core with a small and scoped reproduction

**Comment by rozhanroukhosh** [comment]
@ArnaudBarre Hi Arnaud, Thank you for your reply and full explanation, Sure i will create a bug on the optimizer.

**Comment by stee-ren** [comment]
@ArnaudBarre - I really believe its a guessing game, but I think the optimizer is a red-herring :-) and I fell for this too. Given this seems really specific to MUI & Vite - passing the book to Vite core won't bring anything. It will be closed as a "can't reproduce" obviously.

Why do I believe this is not related to the optimizer?...
If you change the optimizer configuration, it will in turn trigger a re-build - which like I pointed out, has a high chance of clearing the issue. Subsequent changes to your dependencies (also requiring a rebuild, may invariably break things again). At least this was our experience. I tried changing the optimizer settings and I was stunned when it worked - then my euphoria came crashing to the ground days later when I switched branches (where there was some small change in the deps) and after a yarn install - I was back to square one. 

I believe it is why @rozhanroukhosh seemed to have success changing the semvers in her package.json, it triggered a rebuild ( because vite does pay attention to package.json changes and does a rebuild when it notices changes there).
