### ISSUE TITLE
lineNumber error for __source prop

### ISSUE THREAD

**Issue by zjxxxxxxxxx** [vitejs/vite-plugin-react#235]
### Describe the bug

In development, lineNumber for the __source prop provided by [babel-plugin-transform-react-jsx-source](https://babeljs.io/docs/babel-plugin-transform-react-jsx-source) is wrong.

![1697167585043](https://github.com/vitejs/vite-plugin-react/assets/43126836/06b9a682-56b8-44bf-ad8e-6e8ab1495cf5)

I have solved this issue locally and I can submit a pr for this issue.

### Reproduction

https://stackblitz.com/edit/vitejs-vite-nje3zq?file=src%2FApp.tsx&terminal=dev

### Steps to reproduce

Wait for the project to run automatically to see the requests from App.tsx

### System Info

```shell
System:
    OS: macOS 14.0
    CPU: (12) arm64 Apple M2 Pro
    Memory: 3.39 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.19.1 - ~/.nvm/versions/node/v16.19.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.19.1/bin/yarn
    npm: 9.6.2 - ~/.nvm/versions/node/v16.19.1/bin/npm
    pnpm: 8.6.11 - ~/.nvm/versions/node/v16.19.1/bin/pnpm
  Browsers:
    Chrome: 117.0.5938.132
    Safari: 17.0
  npmPackages:
    @vitejs/plugin-legacy: ^4.0.2 => 4.1.1 
    @vitejs/plugin-react: ^4.0.1 => 4.1.0 
    vite: ^4.3.9 => 4.4.11
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite-plugin-react/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite-plugin-react/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite-plugin-react/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite-plugin-react/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ArnaudBarre** [comment]
The issue:

Since https://github.com/vitejs/vite/pull/9590 the pipeline is:
- babel: JSX -> JSX with fast refresh
- esbuild: JSX with fast refresh -> JS with jsxDev calls

The issue is that the first transform drop some line breaks, which then make esbuild put the wrong line number.

To avoid this, the fast refresh transformation should be done at the same time than fast refresh:
- using SWC with the [react-swc plugin](https://github.com/vitejs/vite-plugin-react-swc)
- by using Babel now and adding `` to your config and deps:
```js
export default defineConfig(({ mode }) => {
  return {
    plugins: [
      react({
        babel: {
          plugins:
            mode === 'development'
              ? ['@babel/plugin-transform-react-jsx-development']
              : undefined,
        },
      }),
    ],
  };
});

```

Why this second option is not the default?
Good question, it seems that because esbuild added support jsxDev and at the same time some `restoreJSX` functionality was causing trouble, everything was changed at the same time without taking this issue into account (never though of it before looking into it).
I will look into changing this, I will a do a major in few weeks with Vite 5 release so this could be a good timing.

**Comment by zjxxxxxxxxx** [comment]
I tried to configure retainLines for babel, and it seems to work for now.

```ts
export default defineConfig({
  plugins: [
    react({
      babel: {
        retainLines: isDev,
      },
    }),
  ],
});
```

**Comment by ArnaudBarre** [comment]
Oh nice, I will test which one has the more impact on the dev startup time.
Don't forget to put the babel config behind the dev check, otherwise you will run babel during prod builds:
```js
    plugins: [
      react({
        babel: mode === 'development' ? {
          plugins: ['@babel/plugin-transform-react-jsx-development']    
        } : undefined,
      }),
    ],
```
